In [71]:
import re
import numpy as np
from scipy.spatial import distance

In [2]:
with open ("sentences.txt","r") as file_sent:
    str_list=file_sent.readlines()#.strip()

In [32]:
#str_list

In [4]:
str_clean_list=list(map(str.strip,str_list))

In [5]:
str_clean_lower_list=list(map(str.lower,str_clean_list))

In [6]:
str_c_l_s_list=[re.split('[^a-z]', line) for line in str_clean_lower_list] #list(map(str.split,str_clean_lower_list))

In [7]:
for str_of_file in str_c_l_s_list:
    for i in range(str_of_file.count("")):
        str_of_file.remove("")

In [13]:
set_word=set()
for str_of_file in str_c_l_s_list:
    for word in str_of_file:
        set_word.add(word)

In [15]:
len(set_word)

254

In [55]:
dict_word=dict()
dict_word_reverse=dict()
i=0
for ev_word in set_word:
    dict_word[ev_word]=i
    dict_word_reverse[i]=ev_word
    i+=1

In [64]:
#dict_word_reverse

In [47]:
matr=np.zeros((len(str_list),len(set_word)))

In [41]:
matr

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [58]:
for i in range(matr.shape[0]):  #len(str_list)
    for j in range(matr.shape[1]): #len(set_word)
        matr[i,j]=str_c_l_s_list[i].count(dict_word_reverse[j])

In [66]:
#matr

In [65]:
#str_c_l_s_list

In [98]:
list_of_cos=[distance.cosine(matr[0,:],matr[i,:]) for i in range(matr.shape[0])]

In [113]:
arr_cos=np.array(list_of_cos)
arr_cos

array([0.        , 0.95275444, 0.86447381, 0.89517152, 0.77708871,
       0.94023857, 0.73273876, 0.92587507, 0.88427249, 0.90550888,
       0.83281654, 0.88047714, 0.83964325, 0.87035926, 0.87401184,
       0.94427218, 0.84063619, 0.9566445 , 0.94427218, 0.88854436,
       0.84275727, 0.82503645])

In [112]:
np.argsort(arr_cos)

array([ 0,  6,  4, 21, 10, 12, 16, 20,  2, 13, 14, 11,  8, 19,  3,  9,  7,
        5, 15, 18,  1, 17], dtype=int64)

In [114]:
#help(list)