In [15]:
import pandas as pd
import numpy as np

In [5]:
data=pd.read_csv("checkins.csv")

In [6]:
data2=data.head(100001)[['latitude','longitude']]

In [12]:
dataPred=pd.read_csv("preds.csv")

In [14]:
data2

latitude   longitude
0       38.895112  -77.036366
1       33.800745  -84.410520
2       45.523452 -122.676207
3       40.764462 -111.904565
4       33.448377 -112.074037
5       32.221743 -110.926479
6       40.650000  -73.950000
7       33.448377 -112.074037
8       33.414768 -111.909309
9       42.358431  -71.059773
10      33.448377 -112.074037
11      33.414768 -111.909309
12      33.448377 -112.074037
13      33.248664 -111.634299
14      32.840678 -117.258794
15      34.052234 -118.243685
16      33.414768 -111.909309
17      33.448377 -112.074037
18      34.483901 -114.322455
19      34.048928 -111.093731
20      32.715329 -117.157255
21      33.448377 -112.074037
22      38.895112  -77.036366
23      33.745851 -117.826166
24      34.096111 -118.105833
25      34.052234 -118.243685
26      37.629349 -122.400087
27       4.598056  -74.075833
28      33.804167 -118.158056
29      40.735657  -74.172367
...           ...         ...
99971   34.019454 -118.491191
99972   37.339386 -121.894955
99973   40.650000  -73.950000
99974   43.009703  -85.520024
99975   34.746481  -92.289595
99976   41.763711  -72.685093
99977   44.310000  -96.790000
99978   35.221997 -101.831297
99979   40.740389  -73.983385
99980   33.641132 -117.918669
99981   40.715972  -74.001437
99982   41.033986  -73.762910
99983   27.937801  -82.285925
99984   36.087708  -86.648397
99985   26.203407  -98.230012
99986   40.740389  -73.983385
99987   40.768433  -73.525125
99988   42.866680  -88.333427
99989   40.704824  -73.650130
99990   43.652500  -79.381667
99991   42.372640  -71.109653
99992   35.994033  -78.898619
99993   29.762884  -95.383061
99994   41.878114  -87.629798
99995   33.575000 -117.725556
99996   37.629349 -122.400087
99997   29.762884  -95.383061
99998   32.802955  -96.769923
99999   37.774929 -122.419415
100000  37.798577 -122.424653

[100001 rows x 2 columns]

In [13]:
dataPred

clust
0           5
1           7
2          30
3          65
4           1
5          23
6           0
7           1
8           2
9           8
10          1
11          2
12          1
13        137
14        237
15         11
16          2
17          1
18        507
19         45
20         22
21          1
22          5
23         32
24         47
25         11
26          4
27       1099
28         51
29         48
...       ...
99971      17
99972      20
99973       0
99974     938
99975     325
99976     215
99977    1267
99978     505
99979       0
99980      32
99981       0
99982      74
99983     251
99984      99
99985     536
99986       0
99987      61
99988    1136
99989      61
99990      38
99991       8
99992     151
99993      25
99994       3
99995      50
99996       4
99997      25
99998      19
99999       4
100000      4

[100001 rows x 1 columns]

In [25]:
max_val_clust=dataPred.clust.max()

In [42]:
max_val_clust

3230

In [21]:
num_of_points=dataPred.clust.value_counts() 
#list_center_clust=

In [96]:
num_of_points

0       12506
1        4692
2        3994
4        3527
3        3363
5        2409
6        2297
7        1601
8        1526
9        1378
10       1298
11       1081
13       1007
12       1006
31        907
16        870
15        868
18        808
19        807
22        754
23        747
21        722
14        714
28        679
25        656
17        645
20        612
30        594
26        580
27        577
        ...  
3103        1
2508        1
2988        1
2847        1
2924        1
2806        1
2870        1
3212        1
2911        1
3148        1
2934        1
3084        1
2998        1
3020        1
3062        1
2956        1
3126        1
2892        1
3190        1
2828        1
2860        1
2764        1
2975        1
2700        1
2796        1
2636        1
3039        1
2572        1
2732        1
3030        1
Name: clust, Length: 3231, dtype: int64

In [97]:
list_latit=np.zeros((max_val_clust+1))
list_longit=np.zeros((max_val_clust+1))
num_of_points=dataPred.clust.value_counts() 
for i in range (len(dataPred)):
    #if num_of_points[]
    list_latit[dataPred.clust[i]]+=data2.latitude[i]
    list_longit[dataPred.clust[i]]+=data2.longitude[i]

In [98]:
for i in range (len(list_latit)):
    if num_of_points[i]<16:
        list_latit[i]=0
        list_longit[i]=0
        continue
    list_latit[i]=list_latit[i]/num_of_points[i]
    list_longit[i]=list_longit[i]/num_of_points[i]

In [52]:
list_latit.shape

(3231,)

In [104]:
#list_latit[3]

In [105]:
#list_longit

In [106]:
coord_list=np.vstack((list_latit,list_longit)).T

In [107]:
coord_list

array([[  40.71870687,  -73.99205834],
       [  33.44812108, -112.07375035],
       [  33.45123086, -111.91751966],
       ...,
       [   0.        ,    0.        ],
       [   0.        ,    0.        ],
       [   0.        ,    0.        ]])

In [108]:
#str_coor=coord_list.astype("str",casting='same_kind')

In [109]:
#str_coor

In [110]:
np.savetxt("myarray.txt", coord_list, delimiter=",", fmt=('%f,%f')) #('<U32,<U32')

In [112]:
#help(np.savetxt)

In [132]:
coord_list.shape[0]

3231

In [111]:
#help(coord_list.astype)

In [113]:
offices=np.array([[33.751277, -118.188740],[25.867736, -80.324116],[51.503016, -0.075479],[52.378894, 4.885084],[39.366487, 117.036146],[-33.868457, 151.205134]])

In [133]:
rasst=np.zeros((coord_list.shape[0],offices.shape[0]))
for i in range(coord_list.shape[0]):
    for j in range(offices.shape[0]):
        rasst[i][j]=sum((coord_list[i]-offices[j])**2)**0.5

In [135]:
min_rasst=[min(ras) for ras in rasst]

In [137]:
print(np.argmin(min_rasst))

420


In [139]:
coord_list[420]

array([-33.86063043, 151.20477593])

In [138]:
min_rasst[420]

0.007834758163107856

In [126]:
sum((coord_list[0]-offices[0])**2)**0.5

44.74250494680408

In [50]:
num_of_points.shape

(3231,)

In [33]:
len(dataPred)

100001

In [34]:
dataPred.clust[0]

5

In [38]:
list_latit

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [41]:
list_latit.shape

(3230, 1)